import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Suspense } from "react";
import ProductLoading from "./products/loading";
import { ThemeProvider } from "@/components/theme-provider";
import StoreProvider from "./StoreProvider";
import SiteChrome from "@/components/site-chrome";
import { Toaster } from "@/components/ui/sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <StoreProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <SiteChrome>
              <Suspense fallback={<ProductLoading />}>
                <Toaster />
                {children}
              </Suspense>
            </SiteChrome>
            {/* Suspense use eto stream data if it didn't work it gives skeleton */}
          </ThemeProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
